#!/bin/bash

# Ghi vào file .env.local
cat <<EOF > /.env.local
ADMIN_USER=${ADMIN_USER}
ADMIN_PASS=${ADMIN_PASS}
ADMIN_EMAIL=${ADMIN_EMAIL}
DB_HOST=${DB_HOST}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
GCS_BUCKET=${GCS_BUCKET}
MAIN_TOKEN=${MAIN_TOKEN}
EOF
